### ISSUE TITLE
SuperUserApp is working from command line but not by double clicking of the executable jar

### ISSUE THREAD

**Issue by umesh-m-jadhav** [rritoch/super-user-application#5] opened 2017-02-07 14:22 UTC
Hi Ralph,

I have used same technique i.e extending my main class with SuperUserApplication and now the privileges issue gone out but it is only working in case of running my jar using command line and using command java -jar test.jar

Whenever I double click on the jar, the warning popup opened but nothing progressing. I debug a bit and found that run(String[] args) method is not getting executed.

Do you know how to overcome this issue?

**Comment by rritoch** [comment] 2017-02-07 14:50
umesh-m-jadhav,

Are you running this from a non-removable drive?  I have only seen this problem on windows vista and only when running from a removable drive (such as network drive or USB).  This is basically because the drive isn't available in the administrator environment. Other than that you're going to need to debug the implementation of ISudo to see what parameters are being detected and sent when the jar is re-executed. 

See: https://github.com/rritoch/super-user-application/blob/master/src/main/java/com/vnetpublishing/java/suapp/win/WinSudo.java#L231-L280

**Comment by umesh-m-jadhav** [comment] 2017-02-08 09:08
Hi Ralph,

Thanks for the reply.
I did some detective work at file com.vnetpublishing.java.suapp.win.WinSudo.java

Line 280 - String strparams = toParams(pargs.toArray(new String[pargs.size()]));
Consider my jar is abc.jar and at location C:\Program Files\test\

1. When I run abc.jar at command line using command java -jar abc.jar
    The strparams is coming as "-jar abc.jar" and jar is working perfectly fine.

2. When I run abc.jar by double clicking
     The strparams is coming as "C:\Program Files\test\abc.jar"

I have added patch to format strparams like below

strparams = formatStrParams(strparams);

/**
 * This method will formar the input StrParam.
 *
 * e.g Convert C:\Program Files\test\abc.jar into -jar abc.jar
 * @param param
 * @return
 */
private static String formatStrParams(String param){
	String param_ = "";
	if(param.indexOf('\\')>0){
		int indexOfLast = param.lastIndexOf('\\');
		param_ = param.substring(indexOfLast+1, param.length());
	}
	if(!param.startsWith("-jar"))param_="-jar " + param_;

	return param_;
}

Could you please review this and let us know if it is fine to add this patch? After this patch, jar is working fine.

Also please let us know if you have time to create new jar and publish at git?

**Comment by rritoch** [comment] 2017-02-08 11:49
umesh-m-jadhav,

See line 267-268 and 240, these lines achieve the injection of "-jar " to the parameters as needed.  When sun.java.command parameter is available the system in some cases supports execution outside of a jar such as during the unit tests.  Try dumping the cmd array at https://github.com/rritoch/super-user-application/blob/master/src/main/java/com/vnetpublishing/java/suapp/win/WinSudo.java#L265 as that should detail what the exact problem is.  It may simply be that you have whitespace in the passed parameters causing cmd[0] to be empty which could be more easily resolved by changing 

```
String[] cmd = jcmd.split("\\s+");
```
to

```
String[] cmd = jcmd.trim().split("\\s+");
```

Please let me know what the value of cmd is as that could better debug your specific problem.

**Comment by rritoch** [comment] 2017-02-08 12:06
umesh-m-jadhav,

After further review of your issue, it appears that the problem is the space in the folder name "Program Files".  This will cause the jcmd variable to break up the path as separate arguments.  You should be able to launch your jar with a double click by placing it in a folder without any spaces. There is no way to differentiate between parameters and spaces in a file name which is an ambiguity making this bug impossible to fix for all cases. Alternatively the solution is to create a batch file to launch the jar that you double click on which executes with the short filename by changing to the folder with the jar before executing it.

**Comment by umesh-m-jadhav** [comment] 2017-02-08 15:49
Hi Ralph, yes space is creating the problem. It installed in non spaced folder path and it is working fine

But see, we can't control the user. Application is already installed in 2000 user program file folder.

Would it be possible to create the new jar by fixing this scenario?

**Comment by umesh-m-jadhav** [comment] 2017-02-08 16:13
I think, best way

if(jcmd contains space){
 Just take the jar file name i.e abc.jar
i.e jcmd = abc.jar
}

The flow after String[] cmd = jcmd.split("\\s+"); will work file. I have tested this and working fine.

**Comment by rritoch** [comment] 2017-02-08 18:08
umesh-m-jadhav,

The system is designed to pass command line arguments which are included in the jcmd string and your proposed solution would remove that capability.  If you want to make a custom ISudo implementation for your app based on the one provided that would be a reasonable solution but I am not willing to give up command line arguments in favor of being deployed from folders with spaces.  This is a design trade-off and the best solution is really to use a shell script (batch file) to launch your jar.

This library is released under the MIT license, so you can basically do whatever you want with the code!

You can consider pestering Oracle (java developers) to provide better access to the raw command line arguments which would make it possible to fix this bug but right now there is no reliable means of differentiating between file names with spaces and command line arguments. Even if Oracle updated their specification there is still no guarantee that all implementations would support it. If Oracle (Cheeser, AKA [Justin Lee](https://www.reddit.com/r/reddit.com/comments/ezn2s/freenodes_java_taken_over_by_trolls/) ) finds out this is for a Library I produced they'll likely turn you down flat!

**Closed as completed by rritoch** 2017-02-08 18:08 UTC

**Comment by umesh-m-jadhav** [comment] 2017-02-09 08:38
Thanks my friend. I have added patch at my end. It is working as per our expectation.

**Comment by rritoch** [comment] 2017-02-09 11:52
umesh-m-jadhav,

That is good but the ideal solution is to create your own ISudo and ISuperUserApplication  implementations and extend that instead of SuperUserApplication..

https://github.com/rritoch/super-user-application/blob/master/src/main/java/com/vnetpublishing/java/suapp/SuperUserApplication.java

Based on the patch you mentioned a good class name may be SuperUserJarApp in some namespace for your app.

I'm a strong believer of "If it isn't broken don't fix it" so in your case you can change the architecture in the future if for some reason you need the command line argument support back.

**Comment by umesh-m-jadhav** [comment] 2017-02-09 14:51
Hi,

Yes, I did't change your jar. I have created my own version of WinSudo and SuperUserApplication and I have added my patch inside.

Thanks for your help.

**Comment by sevLax001** [comment] 2020-10-05 00:33
@umesh-m-jadhav  please can you please share your patch am getting this `Error: Could not find or load main class TesProjet.Rooms`
